version: '3.8'

services:
  web:
    build: ./app
    ports:
      - "5001:5000"
    environment:
      - DB_HOST=db
      - DB_NAME=mydatabase
      - DB_USER=user
      - DB_PASSWORD=password
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - mynetwork

volumes:
  db_data:

networks:
  mynetwork:
